# Generated by Django 6.0.4 on 2026-04-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date2',
            field=models.DateField(default='2026-01-01'),
            preserve_default=False,
        ),
    ]
