# Generated by Django 5.0.1 on 2024-03-10 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_api', '0002_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User2',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
