# Generated by Django 6.0.4 on 2026-04-28 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_api', '0002_movie_date2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='date2',
        ),
    ]
