# Generated by Django 6.0.4 on 2026-04-28 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_api', '0003_remove_movie_date2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='date',
        ),
        migrations.AddField(
            model_name='movie',
            name='time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
