# Generated by Django 6.0.4 on 2026-04-28 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_api', '0004_remove_movie_date_movie_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='time',
            new_name='date',
        ),
    ]
