# Generated by Django 6.0.4 on 2026-05-25 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_api', '0005_rename_time_movie_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User2',
            new_name='Guest',
        ),
    ]
